# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
sudo: required
dist: trusty

python:
#  - 2.7
  - 3.4
virtualenv:
    system_site_package: true
before_install:
 - sudo add-apt-repository -y ppa:edd/misc
 - sudo apt-get update
 - sudo apt-get install -qq python-numpy python-six
 - sudo apt-get install libquantlib0-dev
 - pip install -r requirements.txt
install:
    make build
script:
# - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then python -m unittest discover; fi
 - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then python -m unittest discover; fi
notifications:
  email: 
    - stuart.chapman@seronecapital.com
before_deploy:
  cd home/travis/build/stuartjchapman/pyql/quantlib
  zip pyql_sjc
deploy:
#  local_dir: C:\dev\pyql
  provider: releases
  user: "stuartjchapman"
  password: "YaG-fdM-7nQ-7SF"
  file: "pyql_sjc.zip"
  skip_cleanup: true
  overwrite: true 
